name: Verify file

on:
  push:
    branches:
      - main

jobs:
  verify:
    name: ${{ vars.JOB_NAME }}
    if: ${{ vars.EXEC_WF == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - run: echo "${{ vars.FILE_TO_CHECK }} file needs to be added to ${{ github.repository }}"
